version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  random_service:
    build:
      context: ./random-http
    profiles:
      - random

volumes:
  mysql-data:
