version: '2.28.1'

services:
  laravel:
    build:
      context: ./laravel
    volumes:
      - ./laravel:/var/www
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www
    ports:
      - "80:80"
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql

  random-http:
    image: hashicorp/http-echo
    command: ["-text=Hello from random http service!"]
    profiles:
      - random

volumes:
  mysql-data:
